# Generated by Django 5.2.4 on 2025-07-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_student_is_delete_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
