# Generated by Django 5.2.4 on 2025-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
